# Netlify configuration for Swarasync PWA (Static Site)
[build]
  publish = "public"
  command = ""

[build.environment]
  # Disable Next.js plugin
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# HTML files - no cache for dynamic content
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Service Worker - no cache
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# PWA Manifest - light cache
[[headers]]
  for = "/manifest.json"  
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Static assets - long cache
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA-style redirects for clean URLs
[[redirects]]
  from = "/practice"
  to = "/practice.html"
  status = 200

[[redirects]]
  from = "/guide"  
  to = "/guide.html"
  status = 200

# 404 fallback to home
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404